[package]
name = "refractive_swan_test_suite"
version.workspace = true
edition.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
reqwest.workspace = true
serde_json.workspace = true
proptest.workspace = true
serde.workspace = true
once_cell.workspace = true

http-body-util = "0.1"
tower = "0.5"

refractive_swan_api = { path = "../../app/servers/api" }
refractive_swan_datamart = { workspace = true }
refractive_swan_core = { path = "../../domain/core" }
refractive_swan_ingestion = { path = "../../domain/meta/ingestion" }
refractive_swan_mapping = { path = "../../domain/ontologies/mapping" }
refractive_swan_terminology= { path = "../../domain/ontologies/terminology" }
refractive_swan_contracts = { path = "../../domain/meta/contracts" }
refractive_swan_pipeline = { path = "../../domain/meta/pipeline" }
refractive_swan_observability = { path = "../meta/observability" }
refractive_swan_configuration = { path = "../meta/configuration" }
refractive_swan_vector_store = { workspace = true }
refractive_swan_compliance = { path = "../meta/compliance" }
sqlx = { version = "0.7.4", default-features = false, features = ["runtime-tokio", "macros", "sqlite"] }
refractive_swan_eval = { path = "../../domain/meta/evaluation" }
tempfile = "3.10"

[features]
backend-pgvector = ["refractive_swan_vector_store/backend-pgvector"]

[dev-dependencies]
assert_cmd = "2.0"
