[package]
name = "refractive_swan_mesh_hub"
version.workspace = true
edition.workspace = true

[dependencies]
refractive_swan_contracts = { path = "../../../domain/meta/contracts" }
refractive_swan_mesh_dto = { path = "../../../dto/mesh" }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "sync"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror.workspace = true
futures-util.workspace = true
refractive_swan_configuration = { path = "../../meta/configuration" }

[lib]
path = "src/lib.rs"
