[package]
name = "refractive_swan_cache_store"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
async-trait = "0.1.83"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
refractive_swan_configuration = { path = "../../../meta/configuration" }
redis = { version = "0.25", features = ["tokio-comp"] }
