[package]
name = "dfps_eval"
version.workspace = true
edition.workspace = true

[dependencies]
dfps_core = { path = "../core", features = ["dummy"] }
serde.workspace = true
serde_json.workspace = true
rand.workspace = true
sha2 = "0.10"
fake.workspace = true
once_cell.workspace = true
clap.workspace = true
dfps_configuration = { path = "../../platform/configuration" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "eval_bench"
harness = false

[features]
default = []
eval-advanced = []
