[package]
name = "dfps_observability"
version.workspace = true
edition.workspace = true

[dependencies]
dfps_core = { path = "../../domain/core" }
serde = { workspace = true }
serde_json.workspace = true
log = "0.4"
once_cell.workspace = true
dfps_configuration = { path = "../configuration" }
dfps_vector_store = { path = "../../app/servers/vector_store" }
