[package]
name = "dfps_terminology"
version.workspace = true
edition.workspace = true

[features]
default = ["http-client"]
http-client = ["reqwest"]
umls-http = ["http-client"]
ncit-http = ["http-client"]
obo-graph = []

[dependencies]
serde.workspace = true
dfps_core = { path = "../../core" }
dfps_terminology_port = { path = "../../ports/terminology" }
thiserror = "1.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"], optional = true }
once_cell = { workspace = true }
