[package]
name = "refractive_swan_compliance"
version.workspace = true
edition.workspace = true

[dependencies]
refractive_swan_configuration = { path = "../configuration" }
refractive_swan_terminology = { path = "../../../domain/ontologies/terminology" }
serde = { workspace = true }
serde_json.workspace = true
serde_yaml = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
