[package]
name = "refractive_swan_web_frontend"
version.workspace = true
edition.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "refractive_swan_web_frontend"
path = "src/main.rs"

[dependencies]
actix-files.workspace = true
actix-multipart.workspace = true
actix-web.workspace = true
bytes.workspace = true
refractive_swan_core = { path = "../../../domain/core" }
refractive_swan_eval = { path = "../../../domain/meta/evaluation" }
refractive_swan_contracts = { path = "../../../domain/meta/contracts" }
refractive_swan_web_dto = { path = "../../../dto/web" }
refractive_swan_observability = { path = "../../../platform/meta/observability" }
refractive_swan_configuration = { path = "../../../platform/meta/configuration" }
futures-util.workspace = true
maud.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror = "2.0.17"
log = "0.4"
chrono = { version = "0.4.38", default-features = false, features = ["clock"] }
uuid = { version = "1.8.0", features = ["serde", "v4"] }
serde_urlencoded = "0.7"
sha2 = "0.10"
refractive_swan_test_suite = { path = "../../../platform/test_suite" }
refractive_swan_compliance = { path = "../../../platform/meta/compliance" }
refractive_swan_terminology = { path = "../../../domain/ontologies/terminology" }

[dev-dependencies]
wiremock = "0.6"
insta = { version = "1.39.0", features = ["yaml"] }
