#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

out="$root/AGENTS.md"
src_dir="$root/.codex"

mapfile -t shards < <(find "$src_dir" -maxdepth 1 -type f -name '*[0-9][0-9]-*.md' | sort)
mapfile -t crate_shards < <(find "$src_dir/50-crates" -type f -name '*.md' | sort)

{
  echo "<!--- GENERATED by .codex codex-sync. Do not edit directly. --->"
  echo
  echo "# Workspace Rules for Coding Agents (Codex-ready)"
  echo
  echo "> This file is concatenated from \`code/.codex/*.md\` in numeric order so Codex can read one page per directory."
  echo

  for f in "${shards[@]}"; do
    echo
    cat "$f"
    echo
  done

  echo
  echo "## Crate Responsibilities"
  for f in "${crate_shards[@]}"; do
    echo
    cat "$f"
    echo
  done
} > "$out"

echo "Wrote $out"
