#!/usr/bin/env bash
# Sets up a reproducible zsh environment with Oh My Zsh + Powerlevel10k.
# Safe to re-run. Existing configs are backed up before being replaced.

set -euo pipefail

OH_MY_ZSH_DIR="${ZSH:-$HOME/.oh-my-zsh}"
ZSH_CUSTOM="${ZSH_CUSTOM:-$OH_MY_ZSH_DIR/custom}"
P10K_THEME_DIR="$ZSH_CUSTOM/themes/powerlevel10k"
AUTOSUGGESTIONS_DIR="$ZSH_CUSTOM/plugins/zsh-autosuggestions"
SYNTAX_HL_DIR="$ZSH_CUSTOM/plugins/zsh-syntax-highlighting"
ZSHRC_PATH="$HOME/.zshrc"
P10K_CONFIG_PATH="$HOME/.p10k.zsh"

log() {
    printf '[setup-shell] %s\n' "$*"
}

require_command() {
    local cmd="$1"
    local help="$2"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        log "Missing dependency: $cmd"
        log "$help"
        exit 1
    fi
}

backup_file() {
    local file="$1"
    if [[ -f "$file" ]]; then
        local backup="${file}.bak.$(date +%s)"
        cp "$file" "$backup"
        log "Created backup: $backup"
    fi
}

ensure_repo() {
    local repo_url="$1"
    local dest="$2"
    if [[ -d "$dest/.git" ]]; then
        log "Updating $(basename "$dest")..."
        git -C "$dest" pull --ff-only --quiet || true
        return
    fi
    log "Cloning $(basename "$dest")..."
    git clone --depth=1 "$repo_url" "$dest"
}

install_fonts() {
    local os="$(uname -s)"
    local fonts_dir
    case "$os" in
        Linux) fonts_dir="${XDG_DATA_HOME:-$HOME/.local/share}/fonts" ;;
        Darwin) fonts_dir="$HOME/Library/Fonts" ;;
        *) log "Skipping Meslo Nerd Font install (unsupported OS: $os)"; return ;;
    esac

    mkdir -p "$fonts_dir"
    local fonts=(
        "MesloLGS NF Regular.ttf"
        "MesloLGS NF Bold.ttf"
        "MesloLGS NF Italic.ttf"
        "MesloLGS NF Bold Italic.ttf"
    )
    local base_url="https://github.com/romkatv/powerlevel10k-media/raw/master"
    local updated=false

    for font in "${fonts[@]}"; do
        local dest="$fonts_dir/$font"
        if [[ -f "$dest" ]]; then
            continue
        fi
        log "Installing font: $font"
        curl -fsSL "$base_url/${font// /%20}" -o "$dest"
        updated=true
    done

    if [[ "$updated" == true && "$os" == "Linux" ]] && command -v fc-cache >/dev/null 2>&1; then
        log "Refreshing font cache..."
        fc-cache -f "$fonts_dir" >/dev/null 2>&1 || true
    fi
}

write_zshrc() {
    backup_file "$ZSHRC_PATH"
    cat >"$ZSHRC_PATH" <<'EOF'
# Generated by data/ops/scripts/setup_shell.sh (refractive_swan)
export ZSH="$HOME/.oh-my-zsh"
export POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
export POWERLEVEL9K_INSTANT_PROMPT=quiet
export POWERLEVEL9K_MODE=nerdfont-complete

ZSH_THEME="powerlevel10k/powerlevel10k"
plugins=(
  git
  rust
  docker
  docker-compose
  kubectl
  command-not-found
  history-substring-search
  z
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source "$ZSH/oh-my-zsh.sh"

[[ -f "$HOME/.p10k.zsh" ]] && source "$HOME/.p10k.zsh"

# Toolchain locations
export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export CARGO_TARGET_DIR="${CARGO_TARGET_DIR:-$HOME/.cargo-target}"

# Helpful aliases
alias ll='ls -lha'
alias gst='git status -sb'
alias gco='git checkout'
alias gcm='git commit'
alias dcu='docker compose up'
alias dcd='docker compose down'
alias k='kubectl'

# Direnv/Devcontainer helpers
if command -v direnv >/dev/null 2>&1; then
  eval "$(direnv hook zsh)"
fi
if command -v zoxide >/dev/null 2>&1; then
  eval "$(zoxide init zsh)"
fi
if [[ -f "/.dockerenv" || -n "$DEVCONTAINER" ]]; then
  export PROMPT_EOL_MARK=""
fi

# Codex CLI helpers
if [[ -d "$HOME/.codex/bin" ]]; then
  export PATH="$HOME/.codex/bin:$PATH"
fi
EOF
    log "Wrote $ZSHRC_PATH"
}

write_p10k_config() {
    backup_file "$P10K_CONFIG_PATH"
    cat >"$P10K_CONFIG_PATH" <<'EOF'
# Powerlevel10k config tailored for refractive_swan
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  context
  dir
  vcs
  virtualenv
  direnv
  status
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  command_execution_time
  background_jobs
  kubecontext
  time
)
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_SHOW_RULER=true
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%240F> '
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%240F| '
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%240F\\_ '
typeset -g POWERLEVEL9K_TIME_FORMAT='%H:%M:%S'
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
EOF
    log "Wrote $P10K_CONFIG_PATH"
}

main() {
    require_command git "Install Git and re-run this script."
    require_command curl "Install curl and re-run this script."
    require_command zsh "Install zsh via your package manager (apt/brew) and re-run."

    install_fonts
    ensure_repo https://github.com/ohmyzsh/ohmyzsh.git "$OH_MY_ZSH_DIR"
    ensure_repo https://github.com/romkatv/powerlevel10k.git "$P10K_THEME_DIR"
    ensure_repo https://github.com/zsh-users/zsh-autosuggestions.git "$AUTOSUGGESTIONS_DIR"
    ensure_repo https://github.com/zsh-users/zsh-syntax-highlighting.git "$SYNTAX_HL_DIR"

    write_zshrc
    write_p10k_config

    log "Shell setup complete. Run 'chsh -s $(command -v zsh)' to make zsh your default shell (if desired)."
    log "Restart your terminal and select MesloLGS NF as the font for best Powerlevel10k rendering."
}

main "$@"
