[package]
name = "refractive_swan_observability"
version.workspace = true
edition.workspace = true

[dependencies]
refractive_swan_core = { path = "../../../domain/core" }
refractive_swan_vector_port = { path = "../../../domain/ports/data/data-store/vector" }
serde = { workspace = true }
serde_json.workspace = true
log = "0.4"
once_cell.workspace = true
refractive_swan_configuration = { path = "../configuration" }
