[package]
name = "dfps_pipeline"
version.workspace = true
edition.workspace = true

[dependencies]
dfps_ingestion = { path = "../ontologies/ingestion" }
dfps_mapping = { path = "../ontologies/mapping" }
dfps_core = { path = "../core" }
dfps_observability = { path = "../../platform/observability" }
serde = { workspace = true }
serde_json.workspace = true
thiserror = "2.0.17"
log = "0.4"
env_logger = "0.11"
dfps_vector_store = { path = "../../platform/vector_store" }
