[package]
name = "dfps_mapping"
version.workspace = true
edition.workspace = true

[dependencies]
dfps_terminology = { path = "../terminology" }
dfps_core = { path = "../core" }
dfps_eval = { path = "../eval", features = ["eval-advanced"] }
dfps_vector_store = { path = "../../platform/vector_store" }
serde.workspace = true
serde_json.workspace = true
once_cell.workspace = true

[features]
default = ["eval-advanced", "obo-graph"]
eval-advanced = ["dfps_eval/eval-advanced"]
obo-graph = ["dfps_terminology/obo-graph"]
